export const questions= [
  {
    id:1,
    question:'what is the virtual DOM?',
    answer:'virtual DOM is a data structure that describes the structure of a web page',
  },
  {
    id:2,
    question:'How do you create a React app?',
    answer:'Install the create-react-app package using the command prompt or terminal',
  },
  {
    id:3,
    question:'what are synthetic events in React?',
    answer:'Synthetic events are events that are generated by the browser',
  },
  {
    id:4,
    question:'What are the components in React?',
    answer:'Components are independent and reusable bits of code. They serve the same purpose as JavaScript functions, but work in isolation and return HTML' 
   },
   {
    id:5,
    question:'What is the difference between state and props?',
    answer:'State is the data that is shared between components. Props are the data that is passed to the component',
  }
]